import { createContext, useContext, useState } from "react";

export var T = {
  fr: {
    nav: { annonce: "Annonce", protection: "Protection", litige: "Litige", calculateur: "Calculateur", ventes: "Ventes", prix: "Prix" },
    home: {
      title: "La suite complète du revendeur professionnel",
      subtitle: "Annonces optimisées, protection légale avant envoi, et défense automatique contre les fraudes et litiges.",
      beta: "Version Bêta", beta_sub: "Accès 100% gratuit pendant la phase de test",
      m1_title: "Générer une annonce", m1_desc: "Photo → titre, description, hashtags et prix optimisés pour Vinted, Depop, Grailed et plus.", m1_tag: "Gain de temps",
      m2_title: "Protéger mon envoi", m2_desc: "Certifie tes photos avant l’envoi avec horodatage numérique. Preuve légale inattaquable en cas de litige.", m2_tag: "Protection légale",
      m3_title: "Gérer un litige", m3_desc: "Analyse les photos de l’acheteur pour détecter une fraude IA. Génère ta réponse de défense automatiquement.", m3_tag: "Anti-fraude",
      m4_title: "Calculateur", m4_desc: "Calcule tes frais, commissions et marges par plateforme pour fixer le bon prix de vente.", m4_tag: "Rentabilité",
      m5_title: "Mes ventes", m5_desc: "Retrouve l’historique de toutes tes annonces générées et suis tes ventes.", m5_tag: "Suivi",
      m6_title: "Comparer les prix", m6_desc: "Recherche les prix du marché pour un article sur toutes les plateformes en un clic.", m6_tag: "Prix marché",
    },
    annonce: {
      title: "Générer une annonce",
      subtitle: "Photo → annonces optimisées pour toutes les plateformes en 10 secondes.",
      photo_label: "Photos de l’article",
      photo_hint: "Prendre ou choisir des photos",
      photo_sub: "Sélectionne plusieurs photos d’un coup",
      photo_btn: "Prendre ou choisir une photo",
      photo_change: "Changer la photo",
      condition_label: "État de l’article",
      conditions: ["Neuf avec étiquettes", "Neuf sans étiquettes", "Très bon état", "Bon état", "État correct"],
      extra_label: "Infos supplémentaires",
      extra_ph: "Marque, taille, défauts, mesures...",
      btn: "Générer les annonces →",
      loading: "L’IA analyse...",
      generating: "Génération en cours...",
      generate_btn: "Générer les annonces →",
      copy: "Copier", copied: "Copié ✓",
      title_l: "TITRE", desc_l: "DESCRIPTION", kw_l: "HASHTAGS / MOTS-CLÉS", tips_l: "CONSEILS POUR CETTE PLATEFORME",
      share_title: "Mon annonce SellGuard", share_text: "Regarde cette annonce générée par SellGuard", share_btn: "Partager", share_fail: "Partage non disponible",
      measure_title: "MESURES", measure_label: "Type de vêtement",
      measures_label: "Mesures",
      measures_hint: "améliore la précision",
      measures_ph: "Sélectionne un type de vêtement",
      back: "← Nouvelle annonce",
      ai_title: "Analyse IA complète",
      ai_text: "L’IA a analysé la marque, le style et la valeur pour trouver où sont tes acheteurs.",
    },
    protection: {
      title: "Protéger mon envoi",
      subtitle: "Enregistre une vidéo horodatée — preuve solide en cas de litige.",
      video_tab: "🎥 Vidéo", photo_tab: "📷 Photos", recommended: "Recommandé",
      article_label: "Nom de l’article", article_ph: "Ex: Levi’s Trucker Jacket Type 2 - Taille M",
      ref_label: "Référence commande", ref_ph: "Ex: Vinted #4829301", optional: "optionnel",
      activate: "Activer la caméra →",
      start: "⏺ Démarrer l’enregistrement", stop: "⏹ Stop",
      download: "⬇️ Télécharger la preuve vidéo", redo: "Refaire", cancel: "Annuler",
      tips: "Filme l’article, l’étiquette, puis le colis scellé avec le bon de livraison visible. 30 secondes suffisent.",
      certified_title: "Envoi certifié !", certified_sub: "Ta preuve vidéo horodatée a été téléchargée. Conserve ce fichier précieusement.",
      guide_title: "COMMENT UTILISER CETTE PREUVE PAR PLATEFORME", new_btn: "Protéger un autre envoi",
    },
    litige: {
      title: "Gérer un litige",
      subtitle: "L’IA analyse la situation, détecte la fraude et génère ta réponse de défense.",
      type_label: "Type de litige",
      types: ["Article non conforme", "Article prétendument endommagé", "Mauvaise couleur / taille", "Article prétendument non reçu", "Autre"],
      msg_label: "Message de l’acheteur", msg_ph: "Colle ici le message exact de l’acheteur ou la raison du litige...",
      photos_label: "Photos envoyées par l’acheteur", photos_hint: "optionnel — détection de fraude", photos_add: "+ Ajouter les photos de l’acheteur",
      cert_label: "Référence certificat SellGuard", cert_ph: "Ex: SG-ABC123XYZ", cert_hint: "si tu as certifié l’envoi",
      analyze_btn: "Analyser et défendre →", analyzing: "Analyse en cours...", back: "← Retour",
      fraud_label: "Détection de fraude", verdict_l: "ANALYSE DE LA SITUATION", args_l: "TES ARGUMENTS DE DÉFENSE",
      response_l: "RÉPONSE À ENVOYER", steps_l: "PROCHAINES ÉTAPES", copy: "Copier", copied: "Copié ✓",
    },
    calculateur: {
      title: "Calculateur de rentabilité",
      subtitle: "Calcule tes frais, commissions et marge nette par plateforme.",
      price_label: "Prix de vente", price_ph: "Ex: 45",
      cost_label: "Prix d’achat", cost_ph: "Ex: 15",
      shipping_label: "Frais d’envoi", shipping_ph: "Ex: 5",
      platform_label: "Plateforme",
      calculate_btn: "Calculer →",
      commission: "Commission", net: "Revenu net", profit: "Bénéfice", margin: "Marge",
      reset: "← Nouveau calcul",
    },
    ventes: {
      title: "Mes ventes", subtitle: "Historique de toutes tes annonces générées.",
      empty: "Aucune annonce générée pour le moment.", empty_sub: "Utilise le module Annonce pour commencer.",
      clear: "Effacer l’historique", clear_confirm: "Supprimer tout l’historique ?",
      date: "Date", platform: "Plateforme", price: "Prix",
    },
    prix: {
      title: "Comparer les prix", subtitle: "Entre un article et découvre son prix réel sur chaque plateforme.",
      item_label: "Nom de l’article", item_ph: "Ex: Nike Air Force 1 White - Taille 42",
      condition_label: "État",
      conditions: ["Neuf avec étiquettes", "Neuf sans étiquettes", "Très bon état", "Bon état", "État correct"],
      search_btn: "Rechercher les prix →", searching: "Recherche en cours...",
      range: "Fourchette de prix", avg: "Prix moyen", tip: "Conseil", back: "← Nouvelle recherche",
    },
  },
  en: {
    nav: { annonce: "Listing", protection: "Protection", litige: "Dispute", calculateur: "Calculator", ventes: "Sales", prix: "Prices" },
    home: {
      title: "The complete suite for professional resellers",
      subtitle: "Optimized listings, legal protection before shipping, and automatic defense against fraud and disputes.",
      beta: "Beta Version", beta_sub: "100% free access during the testing phase",
      m1_title: "Generate a listing", m1_desc: "Photo → title, description, hashtags and optimized prices for Vinted, Depop, Grailed and more.", m1_tag: "Time saver",
      m2_title: "Protect my shipment", m2_desc: "Certify your photos before shipping with digital timestamping. Unassailable legal proof in case of dispute.", m2_tag: "Legal protection",
      m3_title: "Handle a dispute", m3_desc: "Analyze buyer photos to detect AI fraud. Automatically generates your defense response.", m3_tag: "Anti-fraud",
      m4_title: "Calculator", m4_desc: "Calculate fees, commissions and margins per platform to set the right selling price.", m4_tag: "Profitability",
      m5_title: "My sales", m5_desc: "Find the history of all your generated listings and track your sales.", m5_tag: "Tracking",
      m6_title: "Compare prices", m6_desc: "Search real market prices for any item across all platforms in one click.", m6_tag: "Market prices",
    },
    annonce: {
      title: "Generate a listing",
      subtitle: "Photo → optimized listings for all platforms in 10 seconds.",
      photo_label: "Item photos",
      photo_hint: "Take or choose photos",
      photo_sub: "Select multiple photos at once",
      photo_btn: "Take or choose a photo",
      photo_change: "Change photo",
      condition_label: "Item condition",
      conditions: ["New with tags", "New without tags", "Very good condition", "Good condition", "Fair condition"],
      extra_label: "Additional info", extra_ph: "Brand, size, defects, measurements...",
      btn: "Generate listings →", loading: "AI is analyzing...",
      generating: "Generating...", generate_btn: "Generate listings →",
      copy: "Copy", copied: "Copied ✓",
      title_l: "TITLE", desc_l: "DESCRIPTION", kw_l: "HASHTAGS / KEYWORDS", tips_l: "TIPS FOR THIS PLATFORM",
      share_title: "My SellGuard listing", share_text: "Check out this listing generated by SellGuard", share_btn: "Share", share_fail: "Sharing not available",
      measure_title: "MEASUREMENTS", measure_label: "Clothing type",
      measures_label: "Measurements",
      measures_hint: "improves accuracy",
      measures_ph: "Select a clothing type",
      back: "← New listing",
      ai_title: "Complete AI analysis",
      ai_text: "AI analyzed brand, style and value to find where your buyers actually are.",
    },
    protection: {
      title: "Protect my shipment",
      subtitle: "Record a timestamped video — solid proof in case of a dispute.",
      video_tab: "🎥 Video", photo_tab: "📷 Photos", recommended: "Recommended",
      article_label: "Item name", article_ph: "Ex: Levi's Trucker Jacket Type 2 - Size M",
      ref_label: "Order reference", ref_ph: "Ex: Vinted #4829301", optional: "optional",
      activate: "Activate camera →",
      start: "⏺ Start recording", stop: "⏹ Stop",
      download: "⬇️ Download video proof", redo: "Redo", cancel: "Cancel",
      tips: "Film the item, the label, then the sealed package with the shipping label visible. 30 seconds is enough.",
      certified_title: "Shipment certified!", certified_sub: "Your timestamped video proof has been downloaded. Keep this file safe.",
      guide_title: "HOW TO USE THIS PROOF BY PLATFORM", new_btn: "Protect another shipment",
    },
    litige: {
      title: "Handle a dispute",
      subtitle: "AI analyzes the situation, detects fraud and generates your defense response.",
      type_label: "Dispute type",
      types: ["Item not as described", "Item allegedly damaged", "Wrong color / size", "Item allegedly not received", "Other"],
      msg_label: "Buyer's message", msg_ph: "Paste the buyer's exact message or dispute reason here...",
      photos_label: "Photos sent by buyer", photos_hint: "optional — fraud detection", photos_add: "+ Add buyer's photos",
      cert_label: "SellGuard certificate reference", cert_ph: "Ex: SG-ABC123XYZ", cert_hint: "if you certified the shipment",
      analyze_btn: "Analyze and defend →", analyzing: "Analyzing...", back: "← Back",
      fraud_label: "Fraud detection", verdict_l: "SITUATION ANALYSIS", args_l: "YOUR DEFENSE ARGUMENTS",
      response_l: "RESPONSE TO SEND", steps_l: "NEXT STEPS", copy: "Copy", copied: "Copied ✓",
    },
    calculateur: {
      title: "Profitability calculator",
      subtitle: "Calculate your fees, commissions and net margin per platform.",
      price_label: "Selling price", price_ph: "Ex: 45",
      cost_label: "Purchase price", cost_ph: "Ex: 15",
      shipping_label: "Shipping cost", shipping_ph: "Ex: 5",
      platform_label: "Platform",
      calculate_btn: "Calculate →",
      commission: "Commission", net: "Net revenue", profit: "Profit", margin: "Margin",
      reset: "← New calculation",
    },
    ventes: {
      title: "My sales", subtitle: "History of all your generated listings.",
      empty: "No listings generated yet.", empty_sub: "Use the Listing module to get started.",
      clear: "Clear history", clear_confirm: "Delete all history?",
      date: "Date", platform: "Platform", price: "Price",
    },
    prix: {
      title: "Compare prices", subtitle: "Enter an item and discover its real price on each platform.",
      item_label: "Item name", item_ph: "Ex: Nike Air Force 1 White - Size 9",
      condition_label: "Condition",
      conditions: ["New with tags", "New without tags", "Very good condition", "Good condition", "Fair condition"],
      search_btn: "Search prices →", searching: "Searching...",
      range: "Price range", avg: "Average price", tip: "Tip", back: "← New search",
    },
  }
};

var LangContext = createContext({ lang: "fr", t: T.fr, setLang: function() {} });

export function LangProvider({ children }) {
  var ref = useState("fr"), lang = ref[0], setLang = ref[1];
  return <LangContext.Provider value={{ lang: lang, t: T[lang], setLang: setLang }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
