import { createContext, useContext, useState, useEffect } from "react";

export var T = {
  fr: {
    nav: { annonce: "Annonce", protection: "Protection", litige: "Litige" },
    home: {
      title: "La suite complète du revendeur professionnel",
      subtitle: "Annonces optimisées, protection légale avant envoi, et défense automatique contre les fraudes et litiges.",
      beta: "Version Bêta", beta_sub: "Accès 100% gratuit pendant la phase de test",
      m1_title: "Générer une annonce", m1_desc: "Photo titre, description, hashtags et prix optimisés pour Vinted, Depop, Grailed et plus.", m1_tag: "Gain de temps",
      m2_title: "Protéger mon envoi", m2_desc: "Certifie tes photos avant l’envoi avec horodatage numérique. Preuve légale inattaquable en cas de litige.", m2_tag: "Protection légale",
      m3_title: "Gérer un litige", m3_desc: "Analyse les photos de l’acheteur pour détecter une fraude IA. Génère ta réponse de défense automatiquement.", m3_tag: "Anti-fraude",
    },
    annonce: {
      title: "Générer une annonce",
      subtitle: "Photo annonces optimisées pour toutes les plateformes en 10 secondes.",
      photo_label: "Photos de l’article",
      photo_hint: "Prends ou choisis des photos",
      photo_sub: "Sélectionne plusieurs photos d’un coup",
      photo_btn: "Prends ou choisis une photo",
      photo_change: "Changer la photo",
      condition_label: "État de l’article",
      conditions: ["Neuf avec étiquettes", "Neuf sans étiquettes", "Très bon état", "Bon état", "État correct"],
      extra_label: "Infos supplémentaires",
      extra_ph: "Marque, taille, défauts, mesures...",
      btn: "Générer les annonces",
      loading: "L’IA analyse...",
      generating: "Génération en cours...",
      generate_btn: "Générer les annonces",
      copy: "Copier", copied: "Copié ✓",
      title_l: "TITRE", desc_l: "DESCRIPTION", kw_l: "HASHTAGS / MOTS-CLÉS", tips_l: "CONSEILS POUR CETTE PLATEFORME",
      share_title: "Mon annonce SellCov", share_text: "Regarde cette annonce générée par SellCov", share_btn: "Partager", share_fail: "Partage non disponible",
      measure_title: "MESURES", measure_label: "Type de vêtement",
      measures_label: "Mesures",
      measures_hint: "améliore la précision",
      measures_ph: "Sélectionne un type de vêtement",
      back: "Nouvelle annonce",
      ai_title: "Analyse IA complète",
      ai_text: "L’IA a analysé la marque, le style et la valeur pour trouver où sont tes acheteurs.",
    },
    protection: {
      title: "Protéger mon envoi",
      subtitle: "Enregistre une vidéo horodatée. Preuve solide en cas de litige.",
      video_tab: "Vidéo", photo_tab: "Photos", recommended: "Recommandé",
      article_label: "Nom de l’article", article_ph: "Ex: Single Stitch Tee - Taille S", article_ph_photo: "Ex: Levi's 501 - W30 L32",
      ref_label: "Référence commande", ref_ph: "Ex: Vinted #4829301", optional: "optionnel",
      activate: "Activer la caméra",
      start: "Démarrer l’enregistrement", stop: "Stop",
      download: "Télécharger la preuve vidéo", redo: "Refaire", cancel: "Annuler",
      tips: "Emballe et scelle ton colis avant de lancer la vidéo. Puis filme l’article, le colis fermé et l’étiquette. 30 secondes suffisent.",
      certified_title: "Envoi certifié", certified_sub: "Ta preuve vidéo horodatée a été téléchargée. Conserve ce fichier précieusement.",
      guide_title: "COMMENT UTILISER CETTE PREUVE PAR PLATEFORME", new_btn: "Protéger un autre envoi",
    },
    litige: {
      title: "Gérer un litige",
      subtitle: "L’IA analyse la situation, détecte la fraude et génère ta réponse de défense.",
      type_label: "Type de litige",
      types: ["Article non conforme", "Article prétendument endommagé", "Mauvaise couleur / taille", "Article prétendument non reçu", "Autre"],
      msg_label: "Message de l’acheteur", msg_ph: "Colle ici le message exact de l’acheteur ou la raison du litige...",
      photos_label: "Photos envoyées par l’acheteur", photos_hint: "optionnel, détection de fraude", photos_add: "+ Ajoute les photos de l’acheteur",
      cert_label: "Référence certificat SellCov", cert_ph: "Ex: SC-ABC123XYZ", cert_hint: "si tu as certifié l’envoi",
      analyze_btn: "Analyser et défendre", analyzing: "Analyse en cours...", back: "Retour",
      fraud_label: "Détection de fraude", verdict_l: "ANALYSE DE LA SITUATION", args_l: "TES ARGUMENTS DE DÉFENSE",
      response_l: "RÉPONSE À ENVOYER", steps_l: "PROCHAINES ÉTAPES", copy: "Copier", copied: "Copié ✓",
    },
    calculateur: {
      title: "Calculateur de rentabilité",
      subtitle: "Calcule tes frais, commissions et marge nette par plateforme.",
      price_label: "Prix de vente", price_ph: "Ex: 45",
      cost_label: "Prix d’achat", cost_ph: "Ex: 15",
      shipping_label: "Frais d’envoi", shipping_ph: "Ex: 5",
      platform_label: "Plateforme",
      calculate_btn: "Calculer",
      commission: "Commission", net: "Revenu net", profit: "Bénéfice", margin: "Marge",
      reset: "Nouveau calcul",
    },
    ventes: {
      title: "Mes ventes", subtitle: "Historique de toutes tes annonces générées.",
      empty: "Aucune annonce générée pour le moment.", empty_sub: "Utilise le module Annonce pour commencer.",
      clear: "Effacer l’historique", clear_confirm: "Supprimer tout l’historique ?",
      date: "Date", platform: "Plateforme", price: "Prix",
    },
  },
  en: {
    nav: { annonce: "Listing", protection: "Protection", litige: "Dispute" },
    home: {
      title: "The complete suite for professional resellers",
      subtitle: "Optimized listings, legal protection before shipping, and automatic defense against fraud and disputes.",
      beta: "Beta Version", beta_sub: "100% free access during the testing phase",
      m1_title: "Generate a listing", m1_desc: "Photo title, description, hashtags and optimized prices for Vinted, Depop, Grailed and more.", m1_tag: "Time saver",
      m2_title: "Protect my shipment", m2_desc: "Certify your photos before shipping with digital timestamping. Unassailable legal proof in case of dispute.", m2_tag: "Legal protection",
      m3_title: "Handle a dispute", m3_desc: "Analyze buyer photos to detect AI fraud. Automatically generates your defense response.", m3_tag: "Anti-fraud",
    },
    annonce: {
      title: "Generate a listing",
      subtitle: "Photo optimized listings for all platforms in 10 seconds.",
      photo_label: "Item photos",
      photo_hint: "Take or choose photos",
      photo_sub: "Select multiple photos at once",
      photo_btn: "Take or choose a photo",
      photo_change: "Change photo",
      condition_label: "Item condition",
      conditions: ["New with tags", "New without tags", "Very good condition", "Good condition", "Fair condition"],
      extra_label: "Additional info", extra_ph: "Brand, size, defects, measurements...",
      btn: "Generate listings", loading: "AI is analyzing...",
      generating: "Generating...", generate_btn: "Generate listings",
      copy: "Copy", copied: "Copied ✓",
      title_l: "TITLE", desc_l: "DESCRIPTION", kw_l: "HASHTAGS / KEYWORDS", tips_l: "TIPS FOR THIS PLATFORM",
      share_title: "My SellCov listing", share_text: "Check out this listing generated by SellCov", share_btn: "Share", share_fail: "Sharing not available",
      measure_title: "MEASUREMENTS", measure_label: "Clothing type",
      measures_label: "Measurements",
      measures_hint: "improves accuracy",
      measures_ph: "Select a clothing type",
      back: "New listing",
      ai_title: "Complete AI analysis",
      ai_text: "AI analyzed brand, style and value to find where your buyers actually are.",
    },
    protection: {
      title: "Protect my shipment",
      subtitle: "Record a timestamped video. Solid proof in case of a dispute.",
      video_tab: "Video", photo_tab: "Photos", recommended: "Recommended",
      article_label: "Item name", article_ph: "Ex: Single Stitch Tee - Size S", article_ph_photo: "Ex: Levi's 501 - W30 L32",
      ref_label: "Order reference", ref_ph: "Ex: Vinted #4829301", optional: "optional",
      activate: "Activate camera",
      start: "Start recording", stop: "Stop",
      download: "Download video proof", redo: "Redo", cancel: "Cancel",
      tips: "Pack and seal your parcel before starting the video. Then film the item, the sealed parcel and the label. 30 seconds is enough.",
      certified_title: "Shipment certified", certified_sub: "Your timestamped video proof has been downloaded. Keep this file safe.",
      guide_title: "HOW TO USE THIS PROOF BY PLATFORM", new_btn: "Protect another shipment",
    },
    litige: {
      title: "Handle a dispute",
      subtitle: "AI analyzes the situation, detects fraud and generates your defense response.",
      type_label: "Dispute type",
      types: ["Item not as described", "Item allegedly damaged", "Wrong color / size", "Item allegedly not received", "Other"],
      msg_label: "Buyer's message", msg_ph: "Paste the buyer's exact message or dispute reason here...",
      photos_label: "Photos sent by buyer", photos_hint: "optional, fraud detection", photos_add: "+ Add buyer's photos",
      cert_label: "SellCov certificate reference", cert_ph: "Ex: SC-ABC123XYZ", cert_hint: "if you certified the shipment",
      analyze_btn: "Analyze and defend", analyzing: "Analyzing...", back: "Back",
      fraud_label: "Fraud detection", verdict_l: "SITUATION ANALYSIS", args_l: "YOUR DEFENSE ARGUMENTS",
      response_l: "RESPONSE TO SEND", steps_l: "NEXT STEPS", copy: "Copy", copied: "Copied ✓",
    },
    calculateur: {
      title: "Profitability calculator",
      subtitle: "Calculate your fees, commissions and net margin per platform.",
      price_label: "Selling price", price_ph: "Ex: 45",
      cost_label: "Purchase price", cost_ph: "Ex: 15",
      shipping_label: "Shipping cost", shipping_ph: "Ex: 5",
      platform_label: "Platform",
      calculate_btn: "Calculate",
      commission: "Commission", net: "Net revenue", profit: "Profit", margin: "Margin",
      reset: "New calculation",
    },
    ventes: {
      title: "My sales", subtitle: "History of all your generated listings.",
      empty: "No listings generated yet.", empty_sub: "Use the Listing module to get started.",
      clear: "Clear history", clear_confirm: "Delete all history?",
      date: "Date", platform: "Platform", price: "Price",
    },
  },
  es: {
    nav: { annonce: "Anuncio", protection: "Protección", litige: "Litigio" },
    home: {
      title: "La suite completa del revendedor profesional",
      subtitle: "Anuncios optimizados, protección legal antes del envío y defensa automática contra fraudes.",
      beta: "Versión Beta", beta_sub: "Acceso 100% gratuito durante la fase de prueba",
      m1_title: "Generar un anuncio", m1_desc: "Foto título, descripción, hashtags y precios optimizados.", m1_tag: "Ahorro de tiempo",
      m2_title: "Proteger mi envío", m2_desc: "Certifica tus fotos antes del envío con marca temporal digital.", m2_tag: "Protección legal",
      m3_title: "Gestionar un litigio", m3_desc: "Analiza las fotos del comprador para detectar fraude. Genera tu respuesta de defensa.", m3_tag: "Anti-fraude",
    },
    annonce: {
      title: "Generar un anuncio",
      subtitle: "Foto anuncios optimizados para todas las plataformas en 10 segundos.",
      photo_label: "Fotos del artículo",
      photo_hint: "Tomar o elegir fotos",
      photo_sub: "Selecciona varias fotos a la vez",
      photo_btn: "Tomar o elegir una foto",
      photo_change: "Cambiar la foto",
      condition_label: "Estado del artículo",
      conditions: ["Nuevo con etiquetas", "Nuevo sin etiquetas", "Muy buen estado", "Buen estado", "Estado aceptable"],
      extra_label: "Info adicional", extra_ph: "Marca, talla, defectos, medidas...",
      btn: "Generar anuncios", loading: "La IA analiza...",
      generating: "Generando...", generate_btn: "Generar anuncios",
      copy: "Copiar", copied: "Copiado ✓",
      title_l: "TÍTULO", desc_l: "DESCRIPCIÓN", kw_l: "HASHTAGS / PALABRAS CLAVE", tips_l: "CONSEJOS PARA ESTA PLATAFORMA",
      share_title: "Mi anuncio SellCov", share_text: "Mira este anuncio generado por SellCov", share_btn: "Compartir", share_fail: "Compartir no disponible",
      measure_title: "MEDIDAS", measure_label: "Tipo de prenda",
      measures_label: "Medidas",
      measures_hint: "mejora la precisión",
      measures_ph: "Selecciona un tipo de prenda",
      back: "Nuevo anuncio",
      ai_title: "Análisis IA completo",
      ai_text: "La IA analizó marca, estilo y valor para encontrar dónde están tus compradores.",
    },
    protection: {
      title: "Proteger mi envío",
      subtitle: "Graba un vídeo con marca temporal, prueba sólida en caso de litigio.",
      video_tab: "Vídeo", photo_tab: "Fotos", recommended: "Recomendado",
      article_label: "Nombre del artículo", article_ph: "Ej: Single Stitch Tee - Talla S", article_ph_photo: "Ej: Levi's 501 - W30 L32",
      ref_label: "Referencia del pedido", ref_ph: "Ej: Vinted #4829301", optional: "opcional",
      activate: "Activar cámara",
      start: "Iniciar grabación", stop: "Parar",
      download: "Descargar prueba de vídeo", redo: "Rehacer", cancel: "Cancelar",
      tips: "Empaqueta y sella tu paquete antes de iniciar el vídeo. Luego filma el artículo, el paquete cerrado y la etiqueta. 30 segundos bastan.",
      certified_title: "Envío certificado", certified_sub: "Tu prueba de vídeo con marca temporal ha sido descargada. Guarda este archivo.",
      guide_title: "CÓMO USAR ESTA PRUEBA POR PLATAFORMA", new_btn: "Proteger otro envío",
    },
    litige: {
      title: "Gestionar un litigio",
      subtitle: "La IA analiza la situación, detecta el fraude y genera tu respuesta de defensa.",
      type_label: "Tipo de litigio",
      types: ["Artículo no conforme", "Artículo supuestamente dañado", "Color / talla incorrectos", "Artículo supuestamente no recibido", "Otro"],
      msg_label: "Mensaje del comprador", msg_ph: "Pega aquí el mensaje exacto del comprador...",
      photos_label: "Fotos del comprador", photos_hint: "opcional, detección de fraude", photos_add: "+ Añadir fotos del comprador",
      cert_label: "Referencia certificado SellCov", cert_ph: "Ej: SC-ABC123XYZ", cert_hint: "si certificaste el envío",
      analyze_btn: "Analizar y defender", analyzing: "Analizando...", back: "Volver",
      fraud_label: "Detección de fraude", verdict_l: "ANÁLISIS DE LA SITUACIÓN", args_l: "TUS ARGUMENTOS DE DEFENSA",
      response_l: "RESPUESTA A ENVIAR", steps_l: "PRÓXIMOS PASOS", copy: "Copiar", copied: "Copiado ✓",
    },
    calculateur: {
      title: "Calculadora de rentabilidad", subtitle: "Calcula tus gastos, comisiones y margen neto por plataforma.",
      price_label: "Precio de venta", price_ph: "Ej: 45", cost_label: "Precio de compra", cost_ph: "Ej: 15",
      shipping_label: "Gastos de envío", shipping_ph: "Ej: 5", platform_label: "Plataforma",
      calculate_btn: "Calcular", commission: "Comisión", net: "Ingreso neto", profit: "Beneficio", margin: "Margen", reset: "Nuevo cálculo",
    },
    ventes: { title: "Mis ventas", subtitle: "Historial de todos tus anuncios.", empty: "Ningún anuncio generado.", empty_sub: "Usa el módulo Anuncio.", clear: "Borrar historial", clear_confirm: "¿Borrar todo?", date: "Fecha", platform: "Plataforma", price: "Precio" },
  },
  it: {
    nav: { annonce: "Annuncio", protection: "Protezione", litige: "Controversia" },
    home: {
      title: "La suite completa per il rivenditore professionista",
      subtitle: "Annunci ottimizzati, protezione legale prima della spedizione e difesa automatica contro le frodi.",
      beta: "Versione Beta", beta_sub: "Accesso 100% gratuito durante la fase di test",
      m1_title: "Genera un annuncio", m1_desc: "Foto titolo, descrizione, hashtag e prezzi ottimizzati.", m1_tag: "Risparmio di tempo",
      m2_title: "Proteggi la spedizione", m2_desc: "Certifica le foto prima della spedizione con timestamp digitale.", m2_tag: "Protezione legale",
      m3_title: "Gestisci una controversia", m3_desc: "Analizza le foto dell'acquirente per rilevare frodi. Genera la tua risposta di difesa.", m3_tag: "Anti-frode",
    },
    annonce: {
      title: "Genera un annuncio",
      subtitle: "Foto annunci ottimizzati per tutte le piattaforme in 10 secondi.",
      photo_label: "Foto dell'articolo",
      photo_hint: "Scatta o scegli foto",
      photo_sub: "Seleziona più foto contemporaneamente",
      photo_btn: "Scatta o scegli una foto",
      photo_change: "Cambia foto",
      condition_label: "Stato dell'articolo",
      conditions: ["Nuovo con etichette", "Nuovo senza etichette", "Ottime condizioni", "Buone condizioni", "Condizioni accettabili"],
      extra_label: "Info aggiuntive", extra_ph: "Marca, taglia, difetti, misure...",
      btn: "Genera annunci", loading: "L'IA analizza...",
      generating: "Generazione in corso...", generate_btn: "Genera annunci",
      copy: "Copia", copied: "Copiato ✓",
      title_l: "TITOLO", desc_l: "DESCRIZIONE", kw_l: "HASHTAG / PAROLE CHIAVE", tips_l: "CONSIGLI PER QUESTA PIATTAFORMA",
      share_title: "Il mio annuncio SellCov", share_text: "Guarda questo annuncio generato da SellCov", share_btn: "Condividi", share_fail: "Condivisione non disponibile",
      measure_title: "MISURE", measure_label: "Tipo di indumento",
      measures_label: "Misure",
      measures_hint: "migliora la precisione",
      measures_ph: "Seleziona un tipo di indumento",
      back: "Nuovo annuncio",
      ai_title: "Analisi IA completa",
      ai_text: "L'IA ha analizzato marca, stile e valore per trovare dove sono i tuoi acquirenti.",
    },
    protection: {
      title: "Proteggi la spedizione",
      subtitle: "Registra un video con timestamp, prova solida in caso di controversia.",
      video_tab: "Video", photo_tab: "Foto", recommended: "Consigliato",
      article_label: "Nome dell'articolo", article_ph: "Es: Single Stitch Tee - Taglia S", article_ph_photo: "Es: Levi's 501 - W30 L32",
      ref_label: "Riferimento ordine", ref_ph: "Es: Vinted #4829301", optional: "opzionale",
      activate: "Attiva fotocamera",
      start: "Avvia registrazione", stop: "Stop",
      download: "Scarica prova video", redo: "Rifai", cancel: "Annulla",
      tips: "Imballa e sigilla il pacco prima di avviare il video. Poi filma l'articolo, il pacco chiuso e l'etichetta. 30 secondi bastano.",
      certified_title: "Spedizione certificata", certified_sub: "La tua prova video con timestamp è stata scaricata. Conserva questo file.",
      guide_title: "COME USARE QUESTA PROVA PER PIATTAFORMA", new_btn: "Proteggi un'altra spedizione",
    },
    litige: {
      title: "Gestisci una controversia",
      subtitle: "L'IA analizza la situazione, rileva la frode e genera la tua risposta di difesa.",
      type_label: "Tipo di controversia",
      types: ["Articolo non conforme", "Articolo presumibilmente danneggiato", "Colore / taglia errati", "Articolo presumibilmente non ricevuto", "Altro"],
      msg_label: "Messaggio dell'acquirente", msg_ph: "Incolla qui il messaggio esatto dell'acquirente...",
      photos_label: "Foto dell'acquirente", photos_hint: "opzionale, rilevamento frodi", photos_add: "+ Aggiungi foto dell'acquirente",
      cert_label: "Riferimento certificato SellCov", cert_ph: "Es: SC-ABC123XYZ", cert_hint: "se hai certificato la spedizione",
      analyze_btn: "Analizza e difendi", analyzing: "Analisi in corso...", back: "Indietro",
      fraud_label: "Rilevamento frodi", verdict_l: "ANALISI DELLA SITUAZIONE", args_l: "I TUOI ARGOMENTI DI DIFESA",
      response_l: "RISPOSTA DA INVIARE", steps_l: "PROSSIMI PASSI", copy: "Copia", copied: "Copiato ✓",
    },
    calculateur: {
      title: "Calcolatore di redditività", subtitle: "Calcola le tue spese, commissioni e margine netto per piattaforma.",
      price_label: "Prezzo di vendita", price_ph: "Es: 45", cost_label: "Prezzo d'acquisto", cost_ph: "Es: 15",
      shipping_label: "Costi di spedizione", shipping_ph: "Es: 5", platform_label: "Piattaforma",
      calculate_btn: "Calcola", commission: "Commissione", net: "Entrata netta", profit: "Profitto", margin: "Margine", reset: "Nuovo calcolo",
    },
    ventes: { title: "Le mie vendite", subtitle: "Storico di tutti i tuoi annunci.", empty: "Nessun annuncio generato.", empty_sub: "Usa il modulo Annuncio.", clear: "Cancella storico", clear_confirm: "Cancellare tutto?", date: "Data", platform: "Piattaforma", price: "Prezzo" },
  }
};

var LangContext = createContext({ lang: "fr", t: T.fr, setLang: function() {} });

export function LangProvider({ children }) {
  var ref = useState("fr"), lang = ref[0], setLang0 = ref[1];
  var _mounted = useState(false), mounted = _mounted[0], setMounted = _mounted[1];
  useEffect(function() { try { var saved = localStorage.getItem("sellcov_lang"); if (saved && T[saved]) setLang0(saved); } catch(e) {} setMounted(true); }, []);
  function setLang(l) { setLang0(l); try { localStorage.setItem("sellcov_lang", l); } catch(e) {} }
  return <LangContext.Provider value={{ lang: lang, t: T[lang] || T.fr, setLang: setLang }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
