import { createContext, useContext, useState, useEffect } from "react";

export var T = {
  fr: {
    nav: {
      back: "Retour",
    },
    footer: {
      faq: "FAQ",
      contact: "Contact",
      mentions: "Mentions légales",
      cgu: "CGU",
      confidentialite: "Confidentialité",
      copy: "© 2026 SellCov",
    },
    pros: {
      meta_title: "SellCov — La preuve qui protège ta vente",
      meta_desc: "La preuve vidéo horodatée qui protège chaque vente. Pour les revendeurs vintage qui expédient en volume. Cohorte fondateurs ouverte, sur candidature.",
      og_title: "La preuve qui protège ta vente.",
      og_desc: "Cohorte fondateurs, places limitées.",
      og_image_alt: "SellCov — hérisson et bouclier",

      hero_title_1: "La preuve qui",
      hero_title_2: "protège ta vente.",
      hero_sub: "Pour les revendeurs vintage qui expédient en volume.",
      hero_cta: "Candidater à la cohorte",

      problem_title_1: "Sans preuve,",
      problem_title_2: "l'acheteur a toujours raison.",
      problem_alt: "Voleur qui s'enfuit avec un colis non protégé par SellCov",
      bubble_never: "Jamais reçu",
      bubble_not_conform: "Pas conforme",

      step1_kicker: "Étape 1",
      step1_title_1: "Tu filmes l'envoi",
      step1_title_2: "sans coupure",
      step1_sub: "L'article, l'emballage, la fermeture du colis. Une seule prise, horodatée.",
      step1_alt: "Hérisson qui filme un article avant la mise en colis",

      step2_kicker: "Étape 2",
      step2_title_1: "Un simple message",
      step2_title_2: "suffit.",
      step2_sub: "Mieux vaut prévenir que prouver.",
      step2_alt: "Hérisson qui prévient l'acheteur que l'envoi est certifié SellCov",

      step3_kicker: "Étape 3",
      step3_title_1: "En cas de litige,",
      step3_title_2: "la vidéo plaide pour toi.",
      step3_sub: "Recevable, opposable, imparable.",
      step3_alt: "Tampon de preuve horodatée SellCov",

      offer_title_1: "Place de fondateur,",
      offer_title_2: "limitée.",
      offer_badge_cohort: "Cohorte fondateurs ouverte",
      offer_badge_limit: "Places limitées",
      offer_li_1: "30 jours d'accès complet, sans carte bancaire.",
      offer_li_2: "Mise en place en visio avec le fondateur.",
      offer_li_3: "Certificats vidéo illimités et défense IA.",
      offer_li_4: "Ancrage Bitcoin sur chaque preuve.",
      offer_li_5: "Tarif fondateur verrouillé après les 30 jours, sous le prix public.",
      offer_cta: "Rejoindre la cohorte",
      offer_fineprint: "Contrepartie : un avis sans filtre, et le droit de partager ton succès.",

      form_kicker: "Candidature",
      form_title_1: "Candidate",
      form_title_2: "en deux minutes.",
      form_sub: "Tu candidates, on te répond. 48h max.",
      form_email_label: "Email *",
      form_email_ph: "ton@email.com",
      form_handle_label: "Ton @ Instagram, Discord ou Twitter *",
      form_handle_ph: "@tonpseudo",
      form_platform_label: "Plateforme principale *",
      form_volume_label: "Volume mensuel *",
      form_note_label: "Note (optionnel)",
      form_note_ph: "Une histoire de litige récente, un besoin spécifique, ou pourquoi ça t'intéresse...",
      form_submit: "Envoyer ma candidature",
      form_sending: "Envoi...",
      form_required: "Tous les champs marqués * sont requis.",
      form_network_err: "Erreur réseau, réessaie.",
      form_success_title: "Candidature reçue.",
      form_success_sub: "On revient vers toi sous 48h sur",

      faq_kicker: "Questions fréquentes",
      faq_title_1: "Ce qu'on nous",
      faq_title_2: "demande souvent.",
      faq_q1: "Que se passe-t-il après les 30 jours ?",
      faq_a1: "Si tu continues, tu gardes un tarif fondateur verrouillé, sous le prix public, tant que tu restes. Si tu arrêtes, tu arrêtes. Pas de prélèvement surprise puisqu'on ne t'a jamais demandé ta carte bancaire.",
      faq_q2: "Pourquoi mon Instagram ?",
      faq_a2: "Pour vérifier que tu es un vrai revendeur, pas un compte fictif. On ne te suit pas, on ne te DM pas.",
      faq_q3: "Mes vidéos sont-elles vraiment privées ?",
      faq_a3: "Oui. Tes vidéos sont chiffrées, stockées sur serveurs européens (RGPD), accessibles uniquement depuis ton compte. On ne les visionne pas, on ne les revend pas.",

      platforms: {
        vinted_pro: "Vinted Pro",
        grailed: "Grailed",
        etsy: "Etsy",
        depop: "Depop",
        vestiaire: "Vestiaire Collective",
        autre: "Autre",
      },
      volumes: {
        v30_50: "30 à 50 ventes par mois",
        v50_100: "50 à 100 ventes par mois",
        v100_plus: "100 ventes et plus par mois",
      },
    },
    protection: {
      meta_title: "SellCov — Certifier un envoi",
      title: "Certifier un envoi",
      subtitle: "Une vidéo en une prise, horodatée et signée. La preuve que tu ne peux pas perdre.",

      err_article: "Précise le nom de l'article avant de filmer.",
      err_no_camera_api: "Ton navigateur ne supporte pas la caméra. Essaie Safari ou Chrome récent.",
      err_no_mr: "Ton navigateur ne supporte pas l'enregistrement vidéo. Mets à jour iOS / Safari.",
      err_perm: "Permission caméra refusée. Sur iPhone : tape sur l'icône à gauche de la barre d'adresse → Réglages du site → Caméra → Autoriser. Puis recharge la page.",
      err_notfound: "Aucune caméra trouvée sur cet appareil.",
      err_busy: "La caméra est déjà utilisée par une autre app. Ferme les autres apps caméra puis réessaie.",
      err_overcon: "Cette caméra ne supporte pas la résolution demandée.",
      err_security: "Caméra bloquée pour raisons de sécurité (page non sécurisée ?). Vérifie que l'URL commence bien par https://.",
      err_camera_generic: "Erreur caméra : ",
      err_unknown: "inconnue",
      err_video_create: "Erreur création vidéo : ",
      err_login: "Tu dois être connecté pour certifier un envoi. Va sur /compte.",
      err_init: "Erreur init upload",
      err_storage: "Upload Storage : ",
      err_quota: "Quota journalier atteint (50 certificats / jour). Reset à minuit UTC.",
      err_final: "Erreur finalisation",
      err_generic: "Erreur",

      field_article: "Nom de l'article *",
      ph_article: "Ex : Levi's 501 W30 L32",
      field_ref: "Référence commande (optionnel)",
      ph_ref: "Ex : Vinted #4829301",
      field_carrier: "Transporteur",
      ph_carrier: "Sélectionne un transporteur",
      field_tracking: "Numéro de suivi (optionnel)",
      ph_tracking: "Ex : 6A12345678901",

      how_to_film: "Comment filmer",
      film_step1: "Filme l'article dans tous ses détails (état, défauts, marque, étiquette).",
      film_step2: "Continue en filmant la fermeture complète du colis et la pose de l'étiquette d'envoi.",
      film_step3: "Le tout en une seule prise, sans couper la vidéo.",
      film_time: "Moins de 2 minutes en tout.",

      start_rec: "Démarrer l'enregistrement",
      stop_rec: "Stop et sauvegarder",
      rec_in_progress: "Enregistrement en cours",
      review_text: "Vérifie ton aperçu avant de certifier :",
      certify_now: "Certifier maintenant",
      redo: "Refaire",
      uploading: "Upload et horodatage en cours…",
      do_not_close: "Ne ferme pas cette page.",

      done_title: "Envoi certifié",
      done_sub: "Ton certificat est créé, signé et stocké en sécurité.",
      cert_ref: "Référence certificat",
      download_pdf: "Télécharger le certificat PDF",
      view_verify: "Voir la page de vérification publique",
      track_pkg: "Suivre le colis",
      new_one: "Certifier un autre envoi",

      share_label: "Partage ton expérience",
      copy_link: "Copier le lien",
      copied: "✓ Copié",
      share_x: "Partager sur X",
      share_wa: "WhatsApp",
      share_tweet: "Je viens de certifier ma vente avec SellCov. Preuve vidéo horodatée + signature cryptographique.",
      share_wa_text: "Je viens de certifier ma vente avec SellCov :",

      hash_label: "Hash SHA-256 :",
      timestamp_label: "Horodatage :",
    },
    litige: {
      meta_title: "SellCov — Gérer un litige",
      meta_desc: "Génère une défense automatique pour répondre aux litiges acheteurs.",
      title: "Gérer un litige",
      subtitle: "L'IA analyse la situation, détecte la fraude et génère ta réponse de défense.",
      type_label: "Type de litige",
      type_placeholder: "Sélectionne le type",
      types: [
        "Article non conforme",
        "Article prétendument endommagé",
        "Mauvaise couleur / taille",
        "Article prétendument non reçu",
        "Autre",
      ],
      msg_label: "Message de l'acheteur",
      msg_ph: "Colle ici le message exact de l'acheteur ou la raison du litige...",
      photos_label: "Photos envoyées par l'acheteur",
      photos_hint: "optionnel, détection de fraude",
      photos_add: "+ Ajoute les photos de l'acheteur",
      cert_label: "Référence certificat SellCov",
      cert_ph: "Ex: SC-ABC123XYZ",
      cert_hint: "si tu as certifié l'envoi",
      analyze_btn: "Analyser et défendre",
      analyzing: "Analyse en cours...",
      back: "Retour",
      fraud_label: "Détection de fraude :",
      fraud_high: "Fraude probable",
      fraud_mid: "Suspect",
      fraud_low: "Semble légitime",
      verdict_l: "ANALYSE DE LA SITUATION",
      args_l: "TES ARGUMENTS DE DÉFENSE",
      response_l: "RÉPONSE À ENVOYER",
      steps_l: "PROCHAINES ÉTAPES",
      copy: "Copier",
      copied: "Copié ✓",
      err_login: "Tu dois être connecté pour gérer un litige. Va sur /compte.",
      err_quota: "Quota journalier atteint (10 litiges / jour). Reset à minuit UTC.",
      err_network: "Erreur de connexion. Vérifie ta connexion internet et réessaie.",
      err_overloaded: "Le serveur est occupé. Attends quelques secondes et réessaie.",
      err_generic: "Une erreur est survenue. Réessaie.",
    },
    compte: {
      meta_title: "SellCov — Mon compte",
      meta_desc: "Accède à ton espace SellCov. Gère tes envois certifiés et ton abonnement.",
      loading: "Chargement…",
      title: "Mon compte",
      magic_intro: "Entre ton email. Tu reçois un lien de connexion sécurisé, sans mot de passe.",
      email_ph: "ton@email.com",
      send_link: "Recevoir le lien de connexion",
      sending: "Envoi…",
      err_connect: "Connexion impossible.",
      err_invalid_email: "Email invalide.",
      check_mail: "Vérifie ta boîte mail",
      mail_sent_1: "Un lien de connexion vient d'être envoyé à",
      mail_sent_2: "Clique dessus pour te connecter.",
      change_email: "Changer d'email",

      paid_title: "Paiement confirmé",
      paid_sub: "Ton plan Pro est en cours d'activation. Si l'accès n'est pas immédiat, déconnecte-toi puis reconnecte-toi (ton accès est lu à la connexion).",

      logged_as: "Connecté en tant que",
      logout: "Déconnexion",
      plan_label: "Plan",
      plan_admin: "Admin",
      plan_pro: "Pro",
      plan_free: "Découverte",
      cert_count: "Envois certifiés",

      dash_protection_title: "Certifier un envoi",
      dash_protection_sub: "Filme, horodate, génère ton certificat.",
      dash_litige_title: "Gérer un litige",
      dash_litige_sub: "L'IA monte ta défense en 30 secondes.",

      upgrade_kicker: "Passer au plan Pro",
      upgrade_price_suffix: "/ mois",
      upgrade_desc: "Certificats vidéo illimités, défense IA illimitée, ancrage Bitcoin sur chaque preuve, support prioritaire. Sans engagement, annulable en 1 clic.",
      upgrade_btn: "Passer Pro",
      upgrade_redirect: "Redirection…",
      err_session: "Session expirée, reconnecte-toi.",
      err_checkout: "Erreur lors de la création du paiement.",
      err_network: "Erreur réseau, réessaie.",

      last_envois: "Derniers envois",
      empty_envois: "Aucun envoi certifié pour l'instant.",
      first_envoi_cta: "Certifier mon premier envoi",
      untitled: "Envoi sans titre",
    },
    faq: {
      meta_desc: "Questions fréquentes sur SellCov : preuve vidéo, défense IA, cohorte fondateurs.",
      title: "Questions fréquentes.",
      subtitle: "Tout ce qu'il faut savoir sur SellCov.",
      items: [
        {
          q: "Ma preuve vidéo a-t-elle une valeur juridique ?",
          a: "Oui. Chaque vidéo est horodatée via un hash cryptographique SHA-256. Elle constitue un élément de preuve recevable. La plupart des plateformes acceptent les preuves vidéo dans leur médiation interne.",
        },
        {
          q: "Combien de temps ça prend par envoi ?",
          a: "Moins de 2 minutes.",
        },
        {
          q: "Mes vidéos sont-elles privées ?",
          a: "Totalement. Tes vidéos sont chiffrées, stockées sur des serveurs européens (RGPD), accessibles uniquement depuis ton compte.",
        },
        {
          q: "Que se passe-t-il si la défense automatique échoue ?",
          a: "SellCov te fournit une preuve vidéo horodatée, certifiée SHA-256, recevable en médiation. Cette preuve est solide et reconnue. Elle maximise tes chances, mais ne garantit pas un résultat favorable à 100%. La décision finale appartient à la plateforme ou au tribunal.",
        },
        {
          q: "Que se passe-t-il après les 30 jours de la cohorte fondateurs ?",
          a: "Si tu continues, tu gardes un tarif fondateur verrouillé, sous le prix public, tant que tu restes. Si tu arrêtes, tu arrêtes. Pas de prélèvement surprise puisqu'on ne t'a jamais demandé ta carte bancaire.",
        },
        {
          q: "Pourquoi vous me demandez mon Instagram ?",
          a: "Pour vérifier que tu es un vrai revendeur, pas un compte fictif. On ne te suit pas, on ne te DM pas.",
        },
      ],
    },
    legal_only_fr: "Cette page est disponible uniquement en français. The French version is legally binding.",
  },
  en: {
    nav: {
      back: "Back",
    },
    footer: {
      faq: "FAQ",
      contact: "Contact",
      mentions: "Legal notice",
      cgu: "Terms",
      confidentialite: "Privacy",
      copy: "© 2026 SellCov",
    },
    pros: {
      meta_title: "SellCov — Proof that protects your sale",
      meta_desc: "The timestamped video proof that protects every sale. For vintage resellers who ship in volume. Founders cohort open, by application.",
      og_title: "Proof that protects your sale.",
      og_desc: "Founders cohort, limited spots.",
      og_image_alt: "SellCov — hedgehog and shield",

      hero_title_1: "Proof that",
      hero_title_2: "protects your sale.",
      hero_sub: "For vintage resellers who ship in volume.",
      hero_cta: "Apply to the cohort",

      problem_title_1: "Without proof,",
      problem_title_2: "the buyer is always right.",
      problem_alt: "Thief running off with an unprotected parcel",
      bubble_never: "Never received",
      bubble_not_conform: "Not as described",

      step1_kicker: "Step 1",
      step1_title_1: "Film the shipment",
      step1_title_2: "in one take",
      step1_sub: "The item, the packaging, sealing the box. One single take, timestamped.",
      step1_alt: "Hedgehog filming an item before packing",

      step2_kicker: "Step 2",
      step2_title_1: "A simple message",
      step2_title_2: "is enough.",
      step2_sub: "Better to warn than to prove.",
      step2_alt: "Hedgehog telling the buyer the shipment is SellCov-certified",

      step3_kicker: "Step 3",
      step3_title_1: "If a dispute happens,",
      step3_title_2: "the video speaks for you.",
      step3_sub: "Admissible, enforceable, airtight.",
      step3_alt: "SellCov timestamped proof stamp",

      offer_title_1: "Founder spot,",
      offer_title_2: "limited.",
      offer_badge_cohort: "Founders cohort open",
      offer_badge_limit: "Limited spots",
      offer_li_1: "30 days of full access, no credit card.",
      offer_li_2: "Onboarding video call with the founder.",
      offer_li_3: "Unlimited video certificates and AI defense.",
      offer_li_4: "Bitcoin anchoring on every proof.",
      offer_li_5: "Founder pricing locked after 30 days, below public price.",
      offer_cta: "Join the cohort",
      offer_fineprint: "In exchange: honest feedback, and the right to share your wins.",

      form_kicker: "Application",
      form_title_1: "Apply",
      form_title_2: "in two minutes.",
      form_sub: "You apply, we reply. 48h max.",
      form_email_label: "Email *",
      form_email_ph: "your@email.com",
      form_handle_label: "Your @ on Instagram, Discord or Twitter *",
      form_handle_ph: "@yourhandle",
      form_platform_label: "Main platform *",
      form_volume_label: "Monthly volume *",
      form_note_label: "Note (optional)",
      form_note_ph: "A recent dispute story, a specific need, or why you're interested...",
      form_submit: "Send my application",
      form_sending: "Sending...",
      form_required: "All fields marked * are required.",
      form_network_err: "Network error, try again.",
      form_success_title: "Application received.",
      form_success_sub: "We'll get back to you within 48h at",

      faq_kicker: "Frequently asked",
      faq_title_1: "What we get",
      faq_title_2: "asked the most.",
      faq_q1: "What happens after the 30 days?",
      faq_a1: "If you continue, you keep founder pricing locked below the public price, as long as you stay. If you stop, you stop. No surprise charge since we never asked for your card.",
      faq_q2: "Why my Instagram?",
      faq_a2: "To check you're a real reseller, not a fake account. We don't follow you, we don't DM you.",
      faq_q3: "Are my videos really private?",
      faq_a3: "Yes. Your videos are encrypted, stored on European servers (GDPR), accessible only from your account. We don't watch them, we don't resell them.",

      platforms: {
        vinted_pro: "Vinted Pro",
        grailed: "Grailed",
        etsy: "Etsy",
        depop: "Depop",
        vestiaire: "Vestiaire Collective",
        autre: "Other",
      },
      volumes: {
        v30_50: "30 to 50 sales per month",
        v50_100: "50 to 100 sales per month",
        v100_plus: "100+ sales per month",
      },
    },
    protection: {
      meta_title: "SellCov — Certify a shipment",
      title: "Certify a shipment",
      subtitle: "One single take, timestamped and signed. Proof you can't lose.",

      err_article: "Enter the item name before filming.",
      err_no_camera_api: "Your browser doesn't support camera. Try Safari or a recent Chrome.",
      err_no_mr: "Your browser doesn't support video recording. Update iOS / Safari.",
      err_perm: "Camera permission denied. On iPhone: tap the icon left of the address bar → Site settings → Camera → Allow. Then reload the page.",
      err_notfound: "No camera found on this device.",
      err_busy: "Camera is already in use by another app. Close other camera apps and try again.",
      err_overcon: "This camera doesn't support the requested resolution.",
      err_security: "Camera blocked for security reasons (insecure page?). Check the URL starts with https://.",
      err_camera_generic: "Camera error: ",
      err_unknown: "unknown",
      err_video_create: "Video creation error: ",
      err_login: "You must be logged in to certify a shipment. Go to /compte.",
      err_init: "Upload init error",
      err_storage: "Storage upload: ",
      err_quota: "Daily quota reached (50 certificates / day). Resets at midnight UTC.",
      err_final: "Finalization error",
      err_generic: "Error",

      field_article: "Item name *",
      ph_article: "Ex: Levi's 501 W30 L32",
      field_ref: "Order reference (optional)",
      ph_ref: "Ex: Vinted #4829301",
      field_carrier: "Carrier",
      ph_carrier: "Select a carrier",
      field_tracking: "Tracking number (optional)",
      ph_tracking: "Ex: 6A12345678901",

      how_to_film: "How to film",
      film_step1: "Film the item in detail (condition, defects, brand, label).",
      film_step2: "Continue by filming the full sealing of the parcel and the shipping label.",
      film_step3: "All in one take, without stopping the video.",
      film_time: "Under 2 minutes total.",

      start_rec: "Start recording",
      stop_rec: "Stop and save",
      rec_in_progress: "Recording in progress",
      review_text: "Check your preview before certifying:",
      certify_now: "Certify now",
      redo: "Redo",
      uploading: "Upload and timestamping in progress…",
      do_not_close: "Do not close this page.",

      done_title: "Shipment certified",
      done_sub: "Your certificate is created, signed and stored safely.",
      cert_ref: "Certificate reference",
      download_pdf: "Download PDF certificate",
      view_verify: "View public verification page",
      track_pkg: "Track parcel",
      new_one: "Certify another shipment",

      share_label: "Share your experience",
      copy_link: "Copy link",
      copied: "✓ Copied",
      share_x: "Share on X",
      share_wa: "WhatsApp",
      share_tweet: "I just certified my sale with SellCov. Timestamped video proof + cryptographic signature.",
      share_wa_text: "I just certified my sale with SellCov:",

      hash_label: "SHA-256 hash:",
      timestamp_label: "Timestamp:",
    },
    litige: {
      meta_title: "SellCov — Handle a dispute",
      meta_desc: "Generate an automatic defense to reply to buyer disputes.",
      title: "Handle a dispute",
      subtitle: "AI analyzes the situation, detects fraud and generates your defense response.",
      type_label: "Dispute type",
      type_placeholder: "Select type",
      types: [
        "Item not as described",
        "Item allegedly damaged",
        "Wrong color / size",
        "Item allegedly not received",
        "Other",
      ],
      msg_label: "Buyer's message",
      msg_ph: "Paste the buyer's exact message or dispute reason here...",
      photos_label: "Photos sent by buyer",
      photos_hint: "optional, fraud detection",
      photos_add: "+ Add buyer's photos",
      cert_label: "SellCov certificate reference",
      cert_ph: "Ex: SC-ABC123XYZ",
      cert_hint: "if you certified the shipment",
      analyze_btn: "Analyze and defend",
      analyzing: "Analyzing...",
      back: "Back",
      fraud_label: "Fraud detection:",
      fraud_high: "Likely fraud",
      fraud_mid: "Suspicious",
      fraud_low: "Seems legitimate",
      verdict_l: "SITUATION ANALYSIS",
      args_l: "YOUR DEFENSE ARGUMENTS",
      response_l: "RESPONSE TO SEND",
      steps_l: "NEXT STEPS",
      copy: "Copy",
      copied: "Copied ✓",
      err_login: "You must be logged in to handle a dispute. Go to /compte.",
      err_quota: "Daily quota reached (10 disputes / day). Resets at midnight UTC.",
      err_network: "Connection error. Check your internet and try again.",
      err_overloaded: "Server is busy. Wait a few seconds and try again.",
      err_generic: "Something went wrong. Try again.",
    },
    compte: {
      meta_title: "SellCov — My account",
      meta_desc: "Access your SellCov account. Manage your certified shipments and subscription.",
      loading: "Loading…",
      title: "My account",
      magic_intro: "Enter your email. You'll get a secure login link, no password needed.",
      email_ph: "your@email.com",
      send_link: "Get login link",
      sending: "Sending…",
      err_connect: "Connection failed.",
      err_invalid_email: "Invalid email.",
      check_mail: "Check your inbox",
      mail_sent_1: "A login link was just sent to",
      mail_sent_2: "Click it to log in.",
      change_email: "Change email",

      paid_title: "Payment confirmed",
      paid_sub: "Your Pro plan is being activated. If access isn't immediate, log out then log back in (access is read at login).",

      logged_as: "Logged in as",
      logout: "Log out",
      plan_label: "Plan",
      plan_admin: "Admin",
      plan_pro: "Pro",
      plan_free: "Free",
      cert_count: "Certified shipments",

      dash_protection_title: "Certify a shipment",
      dash_protection_sub: "Film, timestamp, generate your certificate.",
      dash_litige_title: "Handle a dispute",
      dash_litige_sub: "AI builds your defense in 30 seconds.",

      upgrade_kicker: "Upgrade to Pro",
      upgrade_price_suffix: "/ month",
      upgrade_desc: "Unlimited video certificates, unlimited AI defense, Bitcoin anchoring on every proof, priority support. No commitment, cancel in 1 click.",
      upgrade_btn: "Go Pro",
      upgrade_redirect: "Redirecting…",
      err_session: "Session expired, log in again.",
      err_checkout: "Error creating the payment.",
      err_network: "Network error, try again.",

      last_envois: "Recent shipments",
      empty_envois: "No certified shipment yet.",
      first_envoi_cta: "Certify my first shipment",
      untitled: "Untitled shipment",
    },
    faq: {
      meta_desc: "Frequently asked questions about SellCov: video proof, AI defense, founders cohort.",
      title: "Frequently asked.",
      subtitle: "Everything you need to know about SellCov.",
      items: [
        {
          q: "Does my video proof have legal value?",
          a: "Yes. Every video is timestamped through a SHA-256 cryptographic hash. It counts as admissible evidence. Most platforms accept video proof in their internal mediation.",
        },
        {
          q: "How long does it take per shipment?",
          a: "Under 2 minutes.",
        },
        {
          q: "Are my videos private?",
          a: "Fully. Your videos are encrypted, stored on European servers (GDPR), accessible only from your account.",
        },
        {
          q: "What if the automatic defense fails?",
          a: "SellCov gives you a timestamped video proof, SHA-256 certified, admissible in mediation. It's solid and recognized evidence. It maximizes your odds but doesn't guarantee a 100% favorable outcome. The final decision belongs to the platform or court.",
        },
        {
          q: "What happens after the 30 days of the founders cohort?",
          a: "If you continue, you keep founder pricing locked below the public price, as long as you stay. If you stop, you stop. No surprise charge since we never asked for your card.",
        },
        {
          q: "Why do you ask for my Instagram?",
          a: "To check you're a real reseller, not a fake account. We don't follow you, we don't DM you.",
        },
      ],
    },
    legal_only_fr: "This page is only available in French. The French version is legally binding.",
  },
};

var LangContext = createContext({ lang: "fr", t: T.fr, setLang: function() {} });

export function LangProvider({ children }) {
  var ref = useState("fr"), lang = ref[0], setLang0 = ref[1];
  var _mounted = useState(false), mounted = _mounted[0], setMounted = _mounted[1];
  useEffect(function() {
    try {
      var saved = localStorage.getItem("sellcov_lang");
      if (saved && T[saved]) setLang0(saved);
    } catch (e) {}
    setMounted(true);
  }, []);
  useEffect(function() {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
    }
  }, [lang]);
  function setLang(l) {
    if (!T[l]) return;
    setLang0(l);
    try { localStorage.setItem("sellcov_lang", l); } catch (e) {}
  }
  return <LangContext.Provider value={{ lang: lang, t: T[lang] || T.fr, setLang: setLang }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
