import { getSupabaseAdmin } from "../../lib/supabaseAdmin";

// GET /api/certificat?cert_id=SC-XXXXXXXX[&lang=fr]
// Public — retourne le PDF certificat. Pas d'auth nécessaire car le cert_id
// est lui-même la "clé d'accès" : impossible à deviner, partagé par le user.
//
// Le PDF est généré entièrement à partir des données serveur (DB) — aucun
// paramètre client ne peut influencer le contenu. Garantit que le cert
// affiché est bien celui stocké en DB.

const CARRIER_LABELS = {
  colissimo: "Colissimo",
  mondialrelay: "Mondial Relay",
  chronopost: "Chronopost",
  dpd: "DPD",
  ups: "UPS",
  dhl: "DHL",
  laposte: "La Poste",
  autre: "Autre",
};

export default async function handler(req, res) {
  // GET et POST acceptés (compat iOS qui peut bloquer GET pour certains téléchargements)
  const data = req.method === "GET" ? req.query : req.body;
  const certId = data.cert_id;
  const lang = data.lang === "en" ? "en" : "fr";

  if (!certId || typeof certId !== "string" || !/^SC-[A-Z0-9]{8}$/.test(certId)) {
    return res.status(400).json({ error: "Invalid cert_id" });
  }

  // Lookup DB via service_role (bypass RLS pour la page /verify publique)
  const supa = getSupabaseAdmin();
  const { data: cert, error } = await supa
    .from("certificats")
    .select("*")
    .eq("cert_id", certId)
    .single();

  if (error || !cert) {
    return res.status(404).json({ error: "Certificat introuvable" });
  }

  const isEn = lang === "en";
  const t = {
    title: isEn ? "Video Proof Certificate" : "Certificat de Preuve Vidéo",
    certLabel: isEn ? "Certificate: " : "Certificat : ",
    f1: isEn ? "Item" : "Article",
    f2: isEn ? "Order ref." : "Réf. commande",
    f3: isEn ? "Tracking" : "Suivi colis",
    f4: isEn ? "Carrier" : "Transporteur",
    f5: isEn ? "Date & time" : "Date & heure",
    f6: isEn ? "File size" : "Taille fichier",
    f7: isEn ? "SHA-256 hash" : "Empreinte SHA-256",
    f8: isEn ? "Signature" : "Signature",
    infoTitle: isEn ? "How to use this certificate" : "Comment utiliser ce certificat",
    infoText1: isEn
      ? "Submit this PDF + video as proof of shipment condition."
      : "Soumets ce PDF + vidéo comme preuve de l'état de l'envoi.",
    infoText2: isEn
      ? "Verify authenticity at sellcov.com/verify/" + certId
      : "Vérifie l'authenticité sur sellcov.com/verify/" + certId,
    footer: isEn ? "Generated by SellCov" : "Généré par SellCov",
  };

  // Build PDF brut (syntax PDF 1.4 minimal, pas de dep externe)
  // Sanitize : on ne retire PAS les accents (Latin-1 OK), juste les chars hors range Latin-1
  // et les chars qui cassent la syntaxe PDF : ( ) \
  const sanitize = (v, max = 60) =>
    (v || "—").toString().replace(/[^\x20-\xFF]/g, "").replace(/[()\\]/g, "").substring(0, max);

  const sizeKB = cert.video_size_bytes ? Math.round(cert.video_size_bytes / 1024) : "—";
  const dateStr = new Date(cert.created_at).toLocaleString(isEn ? "en-US" : "fr-FR", {
    timeZone: "Europe/Paris",
    dateStyle: "long",
    timeStyle: "medium",
  });

  const fields = [
    [t.f1, sanitize(cert.article)],
    [t.f2, sanitize(cert.order_ref)],
    [t.f3, sanitize(cert.tracking_number)],
    [t.f4, sanitize(CARRIER_LABELS[cert.tracking_carrier] || cert.tracking_carrier)],
    [t.f5, sanitize(dateStr)],
    [t.f6, sanitize(sizeKB) + " KB"],
    [t.f7, sanitize(cert.video_hash, 64)],
    [t.f8, sanitize((cert.tsa_token || "").substring(0, 32) + "...", 40)],
  ];

  const stream = buildStream({ certId, fields, t });
  const objects = [];
  objects.push({ id: 1, content: "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj" });
  objects.push({ id: 2, content: "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj" });
  objects.push({
    id: 4,
    content: `4 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}\nendstream\nendobj`,
  });
  objects.push({
    id: 3,
    content:
      "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >> /F3 << /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >> >> >> >>\nendobj",
  });

  let pdfContent = "%PDF-1.4\n";
  const offsets = {};
  [1, 2, 4, 3].forEach((id) => {
    offsets[id] = pdfContent.length;
    pdfContent += objects.find((o) => o.id === id).content + "\n";
  });
  const xrefOffset = pdfContent.length;
  pdfContent += "xref\n0 5\n0000000000 65535 f \n";
  [1, 2, 3, 4].forEach((id) => {
    pdfContent += String(offsets[id]).padStart(10, "0") + " 00000 n \n";
  });
  pdfContent += `trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="SellCov_${certId}_Certificat.pdf"`);
  res.send(Buffer.from(pdfContent, "latin1"));
}

function buildStream({ certId, fields, t }) {
  const lines = [];

  // Header noir
  lines.push("0 0 0 rg");
  lines.push("0 782 595 60 re f");

  // SellCov title
  lines.push("1 1 1 rg");
  lines.push("BT /F2 22 Tf 40 808 Td (SellCov) Tj ET");
  lines.push("0.035 0.694 0.729 rg");
  lines.push("BT /F1 11 Tf 40 795 Td (" + t.title + ") Tj ET");

  // Cert box vert
  lines.push("0.941 0.992 0.957 rg");
  lines.push("0.522 0.933 0.588 RG");
  lines.push("1 w");
  lines.push("40 720 515 30 re B");
  lines.push("0.082 0.502 0.239 rg");
  lines.push("BT /F2 11 Tf 50 731 Td (" + t.certLabel + certId + ") Tj ET");

  // Fields
  let y = 700;
  fields.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      lines.push("0.976 0.980 0.984 rg");
    } else {
      lines.push("1 1 1 rg");
    }
    lines.push(`40 ${y - 14} 515 18 re f`);
    lines.push("0.533 0.533 0.533 rg");
    lines.push(`BT /F1 9 Tf 45 ${y - 5} Td (${label}) Tj ET`);
    lines.push("0.067 0.067 0.067 rg");
    const isHash = label === t.f7;
    const font = isHash ? "/F3" : "/F1";
    lines.push(`BT ${font} 10 Tf 200 ${y - 5} Td (${value}) Tj ET`);
    y -= 20;
  });

  // Info box
  y -= 15;
  lines.push("0.937 0.965 1.0 rg");
  lines.push("0.749 0.855 0.992 RG");
  lines.push(`40 ${y - 55} 515 60 re B`);
  lines.push("0.114 0.306 0.847 rg");
  lines.push(`BT /F2 9 Tf 48 ${y - 12} Td (${t.infoTitle}) Tj ET`);
  lines.push(`BT /F1 8.5 Tf 48 ${y - 26} Td (${t.infoText1}) Tj ET`);
  lines.push(`BT /F1 8.5 Tf 48 ${y - 38} Td (${t.infoText2}) Tj ET`);

  // Footer
  lines.push("0.969 0.969 0.961 rg");
  lines.push("0 0 595 50 re f");
  lines.push("0.533 0.533 0.533 rg");
  lines.push("BT /F1 8 Tf 40 30 Td (sellcov.com) Tj ET");
  lines.push("BT /F1 8 Tf 40 18 Td (" + t.footer + ") Tj ET");
  lines.push("BT /F1 8 Tf 450 18 Td (" + certId + ") Tj ET");

  return lines.join("\n");
}
