export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();
  
  const { certId, article, orderRef, dateStr, hash, videoSizeKB, deviceInfo, lang } = req.body;

  // Build PDF using raw PDF syntax - no dependencies needed
  const isEn = lang === "en";
  
  const title = isEn ? "Video Proof Certificate" : "Certificat de Preuve Video";
  const f1 = isEn ? "Item" : "Article";
  const f2 = isEn ? "Order ref." : "Ref. commande";
  const f3 = isEn ? "Date & time" : "Date & heure";
  const f4 = isEn ? "Device" : "Appareil";
  const f5 = isEn ? "File size" : "Taille fichier";
  const f6 = isEn ? "SHA-256 hash" : "Empreinte SHA-256";
  const infoTitle = isEn ? "How to use this certificate" : "Comment utiliser ce certificat";
  const infoText1 = isEn 
    ? "Submit this PDF + video as proof of shipment condition." 
    : "Soumettez ce PDF + video comme preuve de l'etat de l'envoi.";
  const infoText2 = isEn
    ? "The SHA-256 hash uniquely identifies your video file."
    : "L'empreinte SHA-256 identifie votre video de facon unique.";
  const footer = isEn ? "Generated by SellGuard" : "Genere par SellGuard";

  const cleanHash = (hash || "").replace(/[^\x20-\x7E]/g, "");
  const cleanArticle = (article || "—").replace(/[^\x20-\x7E]/g, "").substring(0, 40);
  const cleanRef = (orderRef || "—").replace(/[^\x20-\x7E]/g, "").substring(0, 40);
  const cleanDate = (dateStr || "").replace(/[^\x20-\x7E]/g, "");
  const cleanDevice = (deviceInfo || "").replace(/[^\x20-\x7E]/g, "");

  // Build PDF manually
  const lines = [];
  lines.push("%PDF-1.4");
  
  const objects = [];
  
  // Catalog
  objects.push({ id: 1, content: "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj" });
  // Pages
  objects.push({ id: 2, content: "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj" });
  
  // Page content stream
  const stream = buildStream({ certId, cleanArticle, cleanRef, cleanDate, cleanDevice, videoSizeKB, cleanHash, title, f1, f2, f3, f4, f5, f6, infoTitle, infoText1, infoText2, footer });
  
  objects.push({ id: 4, content: `4 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}\nendstream\nendobj` });
  
  // Page
  objects.push({ id: 3, content: "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> /F3 << /Type /Font /Subtype /Type1 /BaseFont /Courier >> >> >> >>\nendobj" });
  
  let pdfContent = "%PDF-1.4\n";
  const offsets = {};
  
  [1, 2, 4, 3].forEach(id => {
    offsets[id] = pdfContent.length;
    pdfContent += objects.find(o => o.id === id).content + "\n";
  });
  
  const xrefOffset = pdfContent.length;
  pdfContent += `xref\n0 5\n0000000000 65535 f \n`;
  [1, 2, 3, 4].forEach(id => {
    pdfContent += String(offsets[id]).padStart(10, "0") + " 00000 n \n";
  });
  pdfContent += `trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="SellGuard_${certId}_Certificat.pdf"`);
  res.send(Buffer.from(pdfContent, "latin1"));
}

function buildStream({ certId, cleanArticle, cleanRef, cleanDate, cleanDevice, videoSizeKB, cleanHash, title, f1, f2, f3, f4, f5, f6, infoTitle, infoText1, infoText2, footer }) {
  const lines = [];
  
  // Header bar
  lines.push("0 0.067 0.067 rg");
  lines.push("0 782 595 60 re f");
  
  // SellGuard title
  lines.push("1 1 1 rg");
  lines.push("BT /F2 22 Tf 40 808 Td (SellGuard) Tj ET");
  lines.push("0.035 0.694 0.729 rg");
  lines.push("BT /F1 11 Tf 40 795 Td (" + title + ") Tj ET");
  
  // Green cert box
  lines.push("0.941 0.992 0.957 rg");
  lines.push("0.522 0.933 0.588 RG");
  lines.push("1 w");
  lines.push("40 720 515 30 re B");
  lines.push("0.082 0.502 0.239 rg");
  lines.push("BT /F2 11 Tf 50 731 Td (Certificate: " + certId + ") Tj ET");
  
  // Fields
  const fields = [
    [f1, cleanArticle],
    [f2, cleanRef],
    [f3, cleanDate],
    [f4, cleanDevice],
    [f5, (videoSizeKB || "—") + " KB"],
    [f6, (cleanHash || "").substring(0, 32)],
  ];
  
  let y = 700;
  fields.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      lines.push("0.976 0.980 0.984 rg");
    } else {
      lines.push("1 1 1 rg");
    }
    lines.push(`40 ${y - 14} 515 18 re f`);
    lines.push("0.533 0.533 0.533 rg");
    lines.push(`BT /F1 9 Tf 45 ${y - 5} Td (${label}) Tj ET`);
    lines.push("0.067 0.067 0.067 rg");
    const font = label === f6 ? "/F3" : "/F1";
    const safeValue = (value || "—").replace(/[()\\]/g, "");
    lines.push(`BT ${font} 10 Tf 200 ${y - 5} Td (${safeValue}) Tj ET`);
    y -= 20;
  });
  
  // Info box
  y -= 15;
  lines.push("0.937 0.965 1.0 rg");
  lines.push("0.749 0.855 0.992 RG");
  lines.push(`40 ${y - 55} 515 60 re B`);
  lines.push("0.114 0.306 0.847 rg");
  lines.push(`BT /F2 9 Tf 48 ${y - 12} Td (${infoTitle}) Tj ET`);
  lines.push(`BT /F1 8.5 Tf 48 ${y - 26} Td (${infoText1}) Tj ET`);
  lines.push(`BT /F1 8.5 Tf 48 ${y - 38} Td (${infoText2}) Tj ET`);
  
  // Footer
  lines.push("0.969 0.969 0.961 rg");
  lines.push("0 0 595 50 re f");
  lines.push("0.533 0.533 0.533 rg");
  lines.push("BT /F1 8 Tf 40 30 Td (sellguard.vercel.app) Tj ET");
  lines.push("BT /F1 8 Tf 40 18 Td (" + footer + ") Tj ET");
  lines.push("BT /F1 8 Tf 450 18 Td (" + certId + ") Tj ET");
  
  return lines.join("\n");
}
